config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :questions do
    member do
      get 'search'
    end
  end
  resources :users
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # def index
  #   if (!params[:keywordSearch])
  #     if (!params[:generation])
  #       @questions = Question.all.page(params[:page]).per(2)
  #     else
  #       @questions = Question.where(generation: params[:generation]).page(params[:page]).per(2)
  #     end
  #   else
  #     @questions = Question.where('title LIKE(?) or description LIKE(?)', "%#{params[:keywordSearch]}%",
  #      "%#{params[:keywordSearch]}%").page(params[:page]).per(2)
  #   end
  # end

  # def new
  #   @question = Question.new
  # end

  # def create
  #   @question = Question.new(question_params)
  #   @question.save
  #   redirect_to (@question)
  # end

  # def show
  # end

  def search
    @questions = Question.where('title LIKE(?) or description LIKE(?)', "%#{params[:keyword]}%", "%#{params[:keyword]}%").limit(1)
    respond_to do |format|
      format.json
    end
  end

 def index
  end

  def new
    @article = Article.new
  end

  def create
    if @article = Article.create(article_params)
      redirect_to action: :show, id: @article.id
    else
      redirect_to action: :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def stocks
    @stocks = Stock.where(user_id: current_user.id, is_stocked: 1)
  end

  def stocks_search
    query = params[:q].values
    @query = query[0]
    @q = Article.ransack(params[:q])
    @articles = @q.result
  end

  def search
    query = params[:q].values
    @query = query[0]
    @q = Article.ransack(params[:q])
    @articles = @q.result
  end

  private
  def article_params
    params.require(:article).permit(
      :user_id,
      :title,
      :body,
      :likes_count
    ).merge(tag_list: params[:article][:tag])
  end

  def move_to_session
    redirect_to "/users/sign_in" unless user_signed_in?
  end




    # @stock = Stock.create(user_id: current_user.id, article_id: params[:article_id], is_stocked: 1)

  # private
  # def question_params
  #   params.require(:question).permit(:description, :title, :image, :image_cache, :remove_image)
  # end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    if (!params[:keywordSearch])
      if (!params[:generation])
        @questions = Question.all.page(params[:page]).per(5)
      else
        @questions = Question.where(generation: params[:generation]).page(params[:page]).per(5)
      end
    else
      @questions = Question.where('title LIKE(?) or description LIKE(?)', "%#{params[:keywordSearch]}%",
       "%#{params[:keywordSearch]}%").page(params[:page]).per(2)
    end
  end

  #def new
    #@question = Question.new
  #end

  def create
    @question = Question.new(question_params)

    @question.save
    redirect_to (@question)
  end

  def show
    @question = Question.includes(:user).find(params[:id])
  end

  def search
    @questions = Question.where('title LIKE(?) or description LIKE(?)', "%#{params[:keyword]}%", "%#{params[:keyword]}%").limit(3)
    respond_to do |format|
      format.json
    end
  end

  private
  def question_params
    params.require(:question).permit(:description, :title, :generation, :image, :image_cache, :remove_image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = User.find(prams[:user_id])
  end



  def show
    @user = User.find(params[:id])
    @id = @user.id
    @articles = Article.all
  end

  def like
    @user = User.find(params[:user_id])
    @id = @user.id
    @articles = Article.all
  end

  def private
    @user = User.find(params[:user_id])
    @id = @user.id
    @articles = Article.all
  end

  def commentpage
    @user = User.find(params[:user_id])
    @id = @user.id
    @articles = Article.all
  end

  def update
    @user = current_user
    judge = params[:judge]

    if judge == "0"
      @user.update(user_params)
      @tags = params[:tag]
      @tag = params[:this_tag]
    else
      @user.update(user_image_params)
      redirect_to action: :show
    end
  end

  private
  def user_params
    params.permit(
      :name,
      :email
    ).merge(tag_list: params[:tag])
  end

  def user_image_params
    params.permit(
      :name,
      :email
    ).merge(image: params[:user][:image])
  end

  def move_to_session
    redirect_to "/users/sign_in" unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article_in.html.haml
.main
  .box-container
    .sidebar
      .sidebar-container
        .question
          =image_tag 'hakase.png',class:"hakase"
          =link_to '質問する', new_article_path
        = button_to articles_path,class: 'tag-list',method: 'get',params:{generation: '中学生'} do
          = image_tag 'tanuki.png',class:"wolf"
          中学生数学
        = button_to articles_path,class: 'tag-list',method: 'get',params:{generation: '高校生'} do
          = image_tag 'wolf.png',class:"wolf"
          高校生数学
        .tag-list#university
          = image_tag 'cow.png',class:"wolf"
          大学生数学
    //= render "articles"
    .articles
      .articles-container
        = render partial: 'question', collection: @questions
      .article-pagenate
        / %from.button_to{:method => "get", :action => "/articles" }
        /   %button.tag-list{:type => "submit"}
        /     もっと見る
        /   %input{:name => "keywordSearch", :type => "hidden", :value => "searchword"}/
        / = button_to articles_path,class: 'tag-list',method: 'get',params:{keywordSearch: 'searchword'} do
        /   もっと見る
        = paginate(@questions)

app/views/articles/_footer.html.haml
//.footer
  //%ul.footer-items
    //%li.footer-item1
      //© 2018 Smaths! Inc.
    //%li.footer-item
      //利用規約
    //%li.footer-item
      //プライバシーポリシー
    //%li.footer-item
      //ヘルプ
    //%li.footer-item2
      //お問い合わせ
    //%li.footer-item
      //smaths!とは

app/views/articles/_header_in.html.haml
.header
  .header-container
    %ul
      %li.header-title
        = link_to questions_path do
          Smaths!
      %li.nav-search-logo
        = image_tag 'search.png',class:"searchicon"
        %li.nav-search-word
          探す
          %input{class: "searchbox",placeholder:'微分 高２',type: "text",id: "searchbox",autocomplete:"off"}
      %li.nav-post
        =link_to '質問する', new_question_path
      %li.nav-mypage
        = image_tag "smile.png",class:'smile'
        .mypage-menu
          .menu-list
            =link_to users_path do
              マイページ
          .menu-list
            あなたがした質問
          .menu-list
            あなたがした回答
          .menu-list
            アカウント設定
          .menu-list
            =link_to destroy_user_session_path(current_user) do
              ログアウト

app/views/articles/_header_question.html.haml
.header
  .header-container
    %ul
      %li.header-title
        = link_to questions_path do
          Smaths!
      %li.nav-search-logo
        = image_tag 'search.png',class:"searchicon"
        %li.nav-search-word
          探す
          .searchbox
            / %input{class: "searchbox",placeholder:'微分 高２',type: "text",id: "searchbox"}
      %li.nav-post

      %li.nav-mypage
        = image_tag "smile.png",class:'smile'
        .mypage-menu
          .menu-list
            =link_to users_path do
              マイページ
          .menu-list
            あなたがした質問
          .menu-list
            あなたがした回答
          .menu-list
            アカウント設定
          .menu-list
            ログアウト

app/views/articles/_question.html.haml
.article
  .article-title
    = question.title
  .article-description
    = question.description
  .article-posttime
    2018/07/24(Tuesday)
  .article-tags
    %ul
      %li.article-tag
        = question.generation
      %li.article-tag
        三角関数
      %li.article-tag
        グラフ

app/views/articles/index.html.haml
//- if user_signed_in?
= render "header_in"
= render "article_in"
//  = render partial: 'article', collection: @articles
//- else
//= render "header_out"
//= render "index_out"
= render "footer"

app/views/articles/new.html.haml
= render 'header_question'

.articlepage-body-new
  .box-container-new
    = form_for @question do |f|
      .question_title
        = f.text_field :title, class: "question_title", placeholder: 'タイトルを入力してください',autocomplete:'off'
      .question_option
        = f.radio_button :generation, '中学生'
        中学生
        = f.radio_button :generation, '高校生'
        高校生
        = f.radio_button :generation, '大学生'
        大学生
        =f.label :image, class: "imagebutton" do
          = f.file_field :image, class: 'imageform', style: 'display:none'
          = image_tag 'imageicon.png',class: 'imageicon',id: 'imageicon'
      .question_box
        = f.text_area :description, class: 'question_box', placeholder: '質問内容を入力してください(1000文字以内)',autocomplete: 'off'
      %img{id:'question_image',style: 'width:280px;height:280px,border:none;'}
      //.question_submit
        //= f.submit '送信', class: 'question_submit_button'
= render 'footer'

app/views/articles/page.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/articles/show.html.haml
= render "header_in"
.show-article-container
  .show-main-body
    .show-main-body-container
      .show-main-article
        .show-main-article-title-container
          .show-main-article-iconholder
            =image_tag 'smile2.png',class:"smile2"
          .show-main-user-name
            Aritomiさんの投稿
          .show-main-article-title
            得意先の社長に責任を取れと言われました得意先の社長に
          .show-main-article-time
            2018/07/31
          %ul.show-main-article-tags
            %li.show-main-article-tags-first
              中学数学
            %li.show-main-article-tags
              三角関数
            %li.show-main-article-tags
              微分
        .show-main-article-question-container
          .show-main-article-question-description-container
            %p.show-main-article-question-description
              与えられた方程式から、x=2を一つの解として持つことが分かるので、二次方程式 x^2 + 2x + 2 - a = 0 が、(i) x = 2 でない重解を持つまたは(ii) 異なる二つの実数解を持ち、その一方が x = 2となればよい。
              与えられた方程式から、x=2を一つの解として持つことが分かるので、二次方程式 x^2 + 2x + 2 - a = 0 が、(i) x = 2 でない重解を持つまたは(ii) 異なる二つの実数解を持ち、その一方が x = 2となればよい。s与えられた方程式から、x=2を一つの解として持つことが分かるので、二次方程式 x^2 + 2x + 2 - a = 0 が、(i) x = 2 でない重解を持つまたは(ii) 異なる二つの実数解を持ち、その一方が x = 2となればよい。
      .show-main-sidebar
        .show-ad-space
          ADspace
  .show-main-answers

= render "footer"

app/views/layouts/application.html.haml
//!!!
//%html
  //%head
    //%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    //%title MathCom
    //= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    //= javascript_include_tag 'application', 'data-turbolinks-track' => true
    //= csrf_meta_tags
    //%link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  //%body
    //= yield

app/views/questions/_article_in.html.haml
.main
  .box-container
    .sidebar
      .sidebar-container
        .question
          =link_to '質問する', new_question_path
        = button_to questions_path,class: 'tag-list',method: 'get',params:{generation: '中学生'} do
          = image_tag 'tanuki.png',class:"wolf"
          中学生数学
        = button_to questions_path,class: 'tag-list',method: 'get',params:{generation: '高校生'} do
          = image_tag 'wolf.png',class:"wolf"
          高校生数学
        = button_to questions_path,class: 'tag-list',method: 'get',params:{generation: '大学生'} do
          = image_tag 'cow.png',class:"wolf"
          大学生数学
    //= render "articles"
    .articles
      .articles-container
        = render partial: 'question', collection: @questions
      .article-pagenate
        
        = paginate(@questions)

app/views/questions/_question.html.haml
.article
  .article-title
    = question.title
  .article-description
    = question.description
  .article-posttime
    2018/07/24(Tuesday)
  .article-tags
    %ul
      %li.article-tag
        = question.generation
      - question.tag_list.each do |tag|
        %li.article-tag
          = tag

app/views/questions/new.html.haml
= render 'header_question'

.articlepage-body-new
  .box-container-new
    = form_for @question do |f|
      .question_title
        = f.text_field :title, class: "question_title", placeholder: 'タイトルを入力してください',autocomplete:'off'
      .question_option
        = f.radio_button :generation, '中学生'
        中学生
        = f.radio_button :generation, '高校生'
        高校生
        = f.radio_button :generation, '大学生'
        大学生

        = f.label :question, :tag_list
        = f.text_field :tag_list, value: @question.tag_list.join(','), class: "form-control"

        =f.label :image, class: "imagebutton" do
          = f.file_field :image, class: 'imageform', style: 'display:none'
          = image_tag 'imageicon.png',class: 'imageicon',id: 'imageicon'
      .question_box
        = f.text_area :description, class: 'question_box', placeholder: '質問内容を入力してください(1000文字以内)',autocomplete: 'off'
      %img{id:'question_image',style: 'width:280px;height:280px,border:none;'}
      .question_submit
        = f.submit '送信', class: 'question_submit_button'
= render 'footer'

app/views/questions/show.html.haml
= render "header_in"
.show-article-container
  .show-main-body
    .show-main-body-container
      .show-main-article
        .show-main-article-title-container
          .show-main-article-iconholder
            =image_tag 'smile2.png',class:"smile2"
          .show-main-user-name
            = @question.user.email
            さんの投稿
          .show-main-article-title
            = @question.title
          .show-main-article-time
            = @question.created_at
          %ul.show-main-article-tags
            %li.show-main-article-tags-first
              = @question.generation
            - @question.tag_list.each do |tag|
              %li.show-main-article-tags
                = tag
        .show-main-article-question-container
          .show-main-article-question-description-container
            %p.show-main-article-question-description
              = @question.description
      .show-main-sidebar
        .show-ad-space
          ADspace
  .show-main-answers

= render "footer"

app/views/users/_didquestion.html.haml
.user-page-userlogs-questions
  .user-page-userlogs-questions-container
    .user-page-userlogs-usericon-container
      %img.user-page-userlogs-usericon{:alt => "", "data-src" => "https://avatars2.githubusercontent.com/u/39428320?v=4", :src => "https://avatars2.githubusercontent.com/u/39428320?v=4", :style => "", :title => ""}/
    .user-page-userlogs-username
      Aritomiさんが 2018/07/26に投稿
    .user-page-userlogs-title
      三角関数のグラフについて三角関数のグラフについて三角関数のグラフ三角関数のグラフについて三角関数のグラフ
.user-page-userlogs-questions
  .user-page-userlogs-questions-container
    .user-page-userlogs-usericon-container
      %img.user-page-userlogs-usericon{:alt => "", "data-src" => "https://avatars2.githubusercontent.com/u/39428320?v=4", :src => "https://avatars2.githubusercontent.com/u/39428320?v=4", :style => "", :title => ""}/
    .user-page-userlogs-username
      Aritomiさんが 2018/07/26に投稿
    .user-page-userlogs-title
      三角関数のグラフについて三角関数のグラフについて三角関数のグラフ三角関数のグラフについて三角関数のグラフ
.user-page-userlogs-questions
  .user-page-userlogs-questions-container
    .user-page-userlogs-usericon-container
      %img.user-page-userlogs-usericon{:alt => "", "data-src" => "https://avatars2.githubusercontent.com/u/39428320?v=4", :src => "https://avatars2.githubusercontent.com/u/39428320?v=4", :style => "", :title => ""}/
    .user-page-userlogs-username
      Aritomiさんが 2018/07/26に投稿
    .user-page-userlogs-title
      三角関数のグラフについて三角関数のグラフについて三角関数のグラフ三角関数のグラフについて三角関数のグラフ
.user-page-userlogs-questions
  .user-page-userlogs-questions-container
    .user-page-userlogs-usericon-container
      %img.user-page-userlogs-usericon{:alt => "", "data-src" => "https://avatars2.githubusercontent.com/u/39428320?v=4", :src => "https://avatars2.githubusercontent.com/u/39428320?v=4", :style => "", :title => ""}/
    .user-page-userlogs-username
      Aritomiさんが 2018/07/26に投稿
    .user-page-userlogs-title
      三角関数のグラフについて三角関数のグラフについて三角関数のグラフ三角関数のグラフについて三角関数のグラフ

app/views/users/_liked.html.haml
- for i in 1..4
  .user-page-userlogs-questions
    .user-page-userlogs-questions-container
      .user-page-userlogs-usericon-container
        = image_tag 'samplehaibara.png',class:'user-page-userlogs-usericon'
      .user-page-userlogs-username
        Aritomiさんが 2018/07/26に投稿
      .user-page-userlogs-title
        三角関数のグラフについて三角関数のグラフについて三角関数のグラフ三角関数のグラフについて三角関数のグラフ

app/views/users/index.html.haml
//= render "articles/header_in"
.userpage-body
  .userpage-container
    .userpage-sidebar
      .userpage-icon-container
        = image_tag 'samplehaibara.png',class:'userpage-icon'
      .userpage-userinfo
        .userpage-username
          = @user.nickname
          .userpage-profile-edit
            プロフィールを編集
        .userpage-userintroduction
          = @user.pr
    .userpage-mainbody
      .userpage-userdata
        .userpage-userdata-container
          aritomiさんのデータ
      .userpage-userlogs
        %ul.userpage-userlogs-details
          .userpage-userlogs-tabs
            %li
              %a.home-tab{href: '#view1'} 質問した投稿
          .userpage-userlogs-tabs
            %li
              %a.magazine-tab{href: '#view2'} 回答した投稿
          .userpage-userlogs-tabs
            %li
              %a.magazine-tab{href: '#view3'} 保存した投稿
      #view1.tab-content
        = render "askedQuestion"
      #view2.tab-content
        = render "answered"
      #view3.tab-content
        = render "liked"
= render "articles/footer"